name: 'Daily Codes'
author: "Talljack"
description: 'To record my daily codes'
inputs:
  token:
    description: 'Your GITHUB_TOKEN'
    required: false
    default: '${{ github.token }}'
outputs:
  dailyCodeInfo:
    description: 'Daily Code Info include username, date, and code'

runs:
  using: 'node16'
  main: 'lib/index.js'

