name: 'Daily Codes Stats'
author: 'Talljack'
description: 'To record my daily codes'

inputs:
  token:
    description: 'Your GITHUB_TOKEN'
    required: false
    default: '${{ github.token }}'
  additionCodeLabel:
    description: 'The label of addition code'
    required: false
    default: 'Addition Codes'
  deletionCodeLabel:
    description: 'The label of deletion code'
    required: false
    default: 'Deletion Codes'
  startDate:
    description: 'The start date of the daily code stats'
    required: false
  endDate:
    description: 'The end date of the daily code stats'
    required: false
  timezoneOffset:
    description: 'Timezone offset in hours (e.g., 8 for UTC+8 Beijing/Shanghai)'
    required: false
    default: '8'
outputs:
  dailyCodeInfo:
    description: 'Daily Code Info include username, date, and code'

runs:
  using: 'node20'
  main: 'lib/index.js'

branding:
  icon: 'code'
  color: 'green'
